### ISSUE TITLE
[question] Why isn't there a program that works with the non-microsoft store version?

### ISSUE THREAD

**Issue by f242** [ysc3839/AppXLauncher#1]
Why isn't there a program that works with the non-microsoft store version?

**Comment by ysc3839** [comment]
What do you mean?

**Comment by f242** [comment]
> What do you mean?

version from https://desktop.telegram.org/

**Comment by ysc3839** [comment]
If you are talking about my other project [FontMod](https://github.com/ysc3839/FontMod). AppXLauncher is just one solution to inject DLL to other program. It's not only for FontMod and Telegram.
Because Telegram fixed the “DLL import hijack”, if you want to inject DLL to non-store version of Telegram, it would require using a separate loader program. And since there's other project doing this job, so I didn't make another one.
But if you are using store version of Telegram, store apps have a debug feature. If it's turned on, when you open the app, system will start the app but pause it, then start the debug program, and the debug program can inject DLL. This method is simpler than the “loader solution” above, and there's no existing project using method, so I make this.

**Comment by f242** [comment]
> there's other project doing this job

please tell me the name of this project, because I could only find this one

**Comment by ysc3839** [comment]
This https://github.com/SpriteOvO/Telegram-Anti-Revoke? But it's not maintained. And I don't know if there's other project.
